"""
i23-2520_Assignment3_DS-A_patch-notebook.py
-----------------
Patches i232520-NLP-Assignment3.ipynb in-place with three improvements:
  1.  Data loading cell → reads cleaned-dataset.csv (no more inline gz parsing)
  2.  Encoder training cell → saves a checkpoint after every epoch and
      auto-resumes from the last saved checkpoint on restart.
  3.  Decoder training cell → same checkpoint save/resume pattern.

Running once:
    python i23-2520_Assignment3_DS-A_patch-notebook.py
Then open / re-run the notebook normally.
"""

import json
from pathlib import Path

NOTEBOOK=Path("i232520-NLP-Assignment3.ipynb")


#──Replacement source code for each cell (stored as plain strings) ──────────

LOAD_DATA_CELL="""\
import pandas as pd

#Loading the pre-cleaned 45k dataset from CSV (generated by data_processor.py)
CLEANED_CSV=BASE_DIR / 'cleaned-dataset.csv'

if not CLEANED_CSV.exists():
    raise FileNotFoundError(
        f'{CLEANED_CSV} not found. Please run data_processor.py first:\\n'
        '    python data_processor.py'
    )

df=pd.read_csv(CLEANED_CSV)

#Converting DataFrame rows into the dict format expected by downstream code
all_data=df[['text','sentiment','len_feat']].to_dict(orient='records')

#Breakdown by category
for cat,grp in df.groupby('category'):
    print(f'Loaded {len(grp):,} samples from {cat}')
print(f'\\nTotal samples: {len(all_data):,}')
"""

TRAIN_ENCODER_CELL="""\
ENCODER_CKPT=MODEL_DIR / 'encoder_checkpoint.pth'

def train_encoder(epochs=12):
    losses=[]
    start_epoch=0

    #Resuming from last saved checkpoint if it exists
    if ENCODER_CKPT.exists():
        ckpt=torch.load(ENCODER_CKPT, map_location=DEVICE)
        model_a.load_state_dict(ckpt['model_state'])
        optimizer_a.load_state_dict(ckpt['optimizer_state'])
        losses=ckpt['losses']
        start_epoch = ckpt['epoch']
        print(f"Encoder: Resuming from epoch {start_epoch} (loss so far: {losses[-1]:.4f})")
    else:
        print('Encoder: Starting fresh training.')

    for ep in range(start_epoch, epochs):
        model_a.train()
        total_loss=0
        #Iterating through batches with progress tracking
        for batch in tqdm(train_loader, desc=f"Encoder Ep {ep+1}/{epochs}"):
            ids, s_tgt, l_tgt=batch['ids'].to(DEVICE), batch['sentiment'].to(DEVICE), batch['len_feat'].to(DEVICE)
            optimizer_a.zero_grad()

            #Performing joint prediction for both tasks
            s_pred, l_pred, _=model_a(ids)
            loss = criterion(s_pred, s_tgt) +criterion(l_pred, l_tgt)

            #Standard backpropagation steps
            loss.backward()
            optimizer_a.step()
            total_loss +=loss.item()

        avg_loss=total_loss /len(train_loader)
        losses.append(avg_loss)
        print(f"Epoch {ep+1} complete. Avg Loss: {avg_loss:.4f}")

        #Saving checkpoint after every epoch so training can be resumed
        torch.save({
            'epoch':           ep+1,
            'model_state':     model_a.state_dict(),
            'optimizer_state': optimizer_a.state_dict(),
            'losses':          losses,
        }, ENCODER_CKPT)
        print(f"  Checkpoint saved -> {ENCODER_CKPT}")

    return losses

#Executing the training process for the encoder
train_losses_a=train_encoder(epochs=12)
"""

TRAIN_DECODER_CELL="""\
DECODER_CKPT=MODEL_DIR /'decoder_checkpoint.pth'

def train_generator(epochs=10,use_rag=True):
    start_epoch=0
    all_losses=[]

    #Resuming from last saved checkpoint if it exists
    if DECODER_CKPT.exists():
        ckpt=torch.load(DECODER_CKPT, map_location=DEVICE)
        model_c.load_state_dict(ckpt['model_state'])
        optimizer_c.load_state_dict(ckpt['optimizer_state'])
        all_losses=ckpt['losses']
        start_epoch=ckpt['epoch']
        print(f"Decoder: Resuming from epoch {start_epoch} (last loss: {all_losses[-1]:.4f})")
    else:
        print('Decoder: Starting fresh training.')

    for ep in range(start_epoch, epochs):
        model_c.train()
        total_loss=0
        for batch in tqdm(train_loader, desc=f"Decoder Ep {ep+1}/{epochs}"):
            batch_ids=[]
            for i in range(len(batch['text'])):
                #Defining reference target for language modeling task
                target="the quality was as expected for this price range"

                #Constructing prompt based on current RAG setting
                ctx=retrieve_top_k(model_a(batch['ids'][i].unsqueeze(0).to(DEVICE))[2][0]) if use_rag else None
                prompt=construct_rag_prompt(batch['text'][i], batch['sentiment'][i].item(),batch['len_feat'][i].item(), ctx)

                #Encoding combined prompt+target into index sequence
                ids=vocab.encode(prompt +target, max_len=128)
                batch_ids.append(torch.tensor(ids))

            x=torch.stack(batch_ids).to(DEVICE)
            optimizer_c.zero_grad()

            #Computing loss on next-token prediction across the sequence
            logits=model_c(x)
            loss=F.cross_entropy(logits[:,:-1,:].reshape(-1,logits.size(-1)), x[:,1:].reshape(-1), ignore_index=0)

            loss.backward()
            optimizer_c.step()
            total_loss +=loss.item()

        avg_loss=total_loss /len(train_loader)
        all_losses.append(avg_loss)
        print(f"Epoch {ep+1} | Loss: {avg_loss:.4f} | Perplexity: {math.exp(avg_loss):.4f}")

        #Saving checkpoint after every epoch so training can be resumed
        torch.save({
            'epoch':           ep+1,
            'model_state':     model_c.state_dict(),
            'optimizer_state': optimizer_c.state_dict(),
            'losses':          all_losses,
        }, DECODER_CKPT)
        print(f"  Checkpoint saved -> {DECODER_CKPT}")

#Start training the grounded generation model
train_generator(epochs=15, use_rag=True)
"""

#Patch source-code functions
def source_lines(code: str):
    """Convert a plain string into the notebook 'source' format (list of lines)."""
    lines = code.splitlines(keepends=True)
    return lines

#identifying cell by id and replacing its content with new code
def patch_cell_by_id(cells,cell_id,new_source):
    for cell in cells:
        if cell.get("id") ==cell_id:
            cell["source"] =source_lines(new_source)
            cell["outputs"]=[]   #clearing stale outputs
            cell["execution_count"]=None
            return True
    return False

#main function to apply patches
def main():
    nb_path=NOTEBOOK
    if not nb_path.exists():
        raise FileNotFoundError(f"Notebook not found: {nb_path}")

    print(f"Reading {nb_path} …")
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    cells=nb["cells"]

    patches=[
        ("load-data-cell", LOAD_DATA_CELL, "Data loading → CSV"),
        ("train-loop-a-cell", TRAIN_ENCODER_CELL, "Encoder training → checkpoint save/resume"),
        ("train-loop-c-cell", TRAIN_DECODER_CELL, "Decoder training → checkpoint save/resume"),
    ]

    for cell_id,new_src,label in patches:
        ok=patch_cell_by_id(cells, cell_id, new_src)
        if ok:
            print(f"[OK]  {label} (cell id={cell_id})")
        else:
            print(f"[WARN] Cell id='{cell_id}' not found – skipping.")

    nb_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False),encoding="utf-8")
    print(f"\nNotebook patched successfully -> {nb_path}")
    print("Done! ✓")

if __name__ =="__main__":
    main()
